config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  resources :orders
  resources :menu_items
  resources :menus
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "welcome#index"

  get "/signin", to: "sessions#new", as: :new_sessions
  post "/signin", to: "sessions#create", as: :sessions
  delete "/signout", to: "sessions#destroy", as: :destroy_sessions

  get "/owner", to: "owner#index", as: :owner
  get "/customer", to: "customer#index", as: :customer
  get "/cart", to: "cart#index", as: :cart
  patch "/cart", to: "cart#update", as: :update_cart
  put "/cart", to: "cart#delete_item", as: :delete_cart_item
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :menu
  has_many :order_items
  validates :name, presence: true
  validates :price, presence: true
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  skip_before_action :ensure_user_is_owner, only: [:index, :show]

  def new
    @current_menu_id = params[:menu_id]
    @menu = Menu.find(@current_menu_id).name.capitalize
  end

  def show
    @menuItem = MenuItem.find_by(id: params[:id], deletable: nil)
    @menu_id = params[:menu_id]
    @is_customer = customer
    @is_owner = owner
  end

  def create
    name = params[:name].capitalize
    description = params[:description]
    price = params[:price]
    menu_id = params[:menu_id]
    menuItem = MenuItem.new(name: name, menu_id: menu_id, description: description, price: price)
    if menuItem.save
      redirect_to menu_path(:id => menu_id), notice: "#{name} item was successfully created!"
    else
      flash[:error] = menuItem.errors.full_messages.join(", ")
      redirect_to new_menu_item_path(menu_id: menu_id)
    end
  end

  def destroy
    menu_id = params[:menu_id]
    item = MenuItem.find(params[:id])
    name = item.name.capitalize
    item.deletable = true
    item.save
    redirect_to menu_path(:id => menu_id), notice: "#{name} item was successfully deleted!"
  end

  def update
    @menu_item = MenuItem.find(params[:id])
    name = params[:name].capitalize
    description = params[:description]
    price = params[:price]
    menu_id = params[:menu_id]
    menuItem = MenuItem.update(@menu_item.id, name: name, menu_id: menu_id, description: description, price: price)
    if menuItem.save
      redirect_to menu_item_path(menu_id: menu_id), notice: "#{name} item was successfully updated!"
    else
      flash[:error] = menuItem.errors.full_messages.join(", ")
      redirect_to menu_item_path(menu_id: menu_id)
    end
  end
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/views/menu_items/_edit.html.erb
<h2 class=" pb-5 pt-20 text-4xl ml-40">Edit item</h2>
<section class="form mx-40 my-10 ">
  <%= form_with url: menu_item_path(menu_item.id) ,method: "put" do |form|%>
    <p> <%= form.label :name, "Item name" %></p>
    <%= form.text_field :name ,class:"form-input my-4 text-center",value: menu_item.name%>
    <p>  <%= form.label :description, "Description" %></p>
    <%= form.text_area :description, size: "40x4" ,class:"form-input my-4 text-center",value: menu_item.description%>
    <p>  <%= form.label :price, "Price" %></p>
    <%= form.number_field :price ,step: 0.5,class:"form-input my-4 text-center",value: menu_item.price%>
    <%= form.hidden_field :menu_id,:value => menu_id %>
    <div> <%= form.submit "Update",class:"form-btn my-5"%></div>
  <% end %>
</section>

app/views/menu_items/new.html.erb
<h2 class=" pb-10 text-4xl ml-40"><%= @menu %></h2>
<section class="form mx-40 my-10 ">
  <%= form_with url: menu_items_path do |form|%>
    <p> <%= form.label :name, "Item name" %></p>
    <%= form.text_field :name ,class:"form-input my-4"%>
    <p>  <%= form.label :description, "Description" %></p>
    <%= form.text_area :description, size: "40x4" ,class:"form-input my-4"%>
    <p>  <%= form.label :price, "Price" %></p>
    <%= form.number_field :price ,step: 0.5,class:"form-input my-4"%>
    <%= form.hidden_field :menu_id,:value => @current_menu_id,class:"form-input my-4" %>
    <div> <%= form.submit "Add",class:"form-btn my-5"%></div>
  <% end %>
</section>

app/views/menu_items/show.html.erb
<section class="flex space-y-10 flex-col">
  <h1 class="  mx-auto"><%=@menuItem.name.capitalize %></h1>
  <p class=" whitespace-pre-wrap mx-20 text-center"><%= @menuItem.description %></p>
  <h2 class="text-center  text-5xl text-green-800">$<%= @menuItem.price%></h2>
</section>
<% if @is_customer%>
  <section class=" mx-auto flex flex-col my-10 text-center ">
    <%= form_with url:update_cart_path(id: @menuItem.id),method: "patch" do |form|%>
      <p class="my-5 "> <%= form.label :quantity,"How many would you like to buy?"%></p>
      <%= form.number_field :quantity ,step: 1,class:"form-input text-center mx-40"%>
      <div> <%= form.submit "Add to cart!",class: "btn text-2xl text-center py-4 px-14 my-5  bg-green-400 " %></div>
    <% end %>
  <% end %>
  <% if @is_owner%>
    <%= render partial: "edit",locals:{menu_item: @menuItem,menu_id: @menu_id}%>
  <% end %>
</section>