config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  resources :orders
  resources :menu_items
  resources :menus
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "welcome#index"

  get "/signin", to: "sessions#new", as: :new_sessions
  post "/signin", to: "sessions#create", as: :sessions
  delete "/signout", to: "sessions#destroy", as: :destroy_sessions

  get "/owner", to: "owner#index", as: :owner
  get "/customer", to: "customer#index", as: :customer
  get "/cart", to: "cart#index", as: :cart
  patch "/cart", to: "cart#update", as: :update_cart
  put "/cart", to: "cart#delete_item", as: :delete_cart_item
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :menu_items
  validates :name, presence: true
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :menu
  has_many :order_items
  validates :name, presence: true
  validates :price, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :menu_item
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :orders
  validates :email, presence: true
  validates :password, presence: true
  validates :password, length: { minimum: 5 }
  validates :name, presence: true
  validates :email, uniqueness: true
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  skip_before_action :ensure_user_is_owner

  def index
    @cart = session[:cart]
    @total = 0
    if @cart
      @cart.each do |cartItem|
        price = MenuItem.find(cartItem["menu_item_id"]).price
        @total += price * cartItem["quantity"]
      end
    end
  end

  def update
    menu_item_id = params[:id]
    quantity = params[:quantity].to_i
    if quantity < 1
      flash[:error] = "Please add atleast one item!"
      redirect_to menu_item_path(menu_item_id) and return
    end
    if session[:cart].any? { |item| item["menu_item_id"] == menu_item_id }
      session[:cart].map { |item| item["quantity"] += quantity if item["menu_item_id"] == menu_item_id }

      redirect_to cart_path, notice: "Added #{quantity} more of #{MenuItem.find(menu_item_id).name} to cart!"
    else
      session[:cart].push({ "menu_item_id" => menu_item_id, "quantity" => quantity.to_i })
      redirect_to cart_path, notice: "Added #{MenuItem.find(menu_item_id).name} to cart!"
    end
  end

  def delete_item
    menu_item_id = params[:id]
    session[:cart].reject! { |item| item["menu_item_id"] == menu_item_id }
    redirect_to cart_path, notice: "Deleted  #{MenuItem.find(menu_item_id).name} from cart!"
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    @menus = Menu.all

    render "index"
  end

  def create
    name = params[:name].capitalize
    menu = Menu.new(name: name)
    if menu.save
      redirect_to owner_path, notice: "#{name} menu was successfully created!"
    else
      flash[:error] = menu.errors.full_messages.join(", ")
      redirect_to new_menu_path
    end
  end

  def show
    @is_owner = ensure_user_is_owner
    @current_menu_id = params[:id]
    @menu_items = MenuItem.where(menu_id: @current_menu_id, deletable: nil)
    @menu = Menu.find(@current_menu_id)
    if MenuItem.where(menu_id: @current_menu_id, deletable: nil).empty?
      @menu.active = nil
      @menu.save
      flash[:error] = "#{@menu.name} menu is empty! Setting it to inactive!"
    end
    render "show"
  end

  def update
    active_status = params[:active]
    menu = Menu.find(params[:id])
    if active_status
      if Menu.where(active: true).any?
        flash[:error] = "#{Menu.find_by(active: true).name} menu is already active!"
        redirect_to menu_path(params[:id]) and return
      elsif MenuItem.where(menu_id: menu.id, deletable: nil).empty?
        flash[:error] = "#{menu.name} menu is empty! Cannot set it active!"
        redirect_to menu_path(params[:id]) and return
      end
    end
    menu.active = active_status
    menu.save
    redirect_to menu_path(:id => menu.id), notice: "#{menu.name.capitalize} menu was successfully set #{active_status ? true : false}!"
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :ensure_user_is_owner

  def index
    @is_customer = customer
    @is_owner = owner
    @orders = Order.all
    @orders_customer = Order.where(user_id: session[:current_user_id])
  end

  def new
    total = params[:total]
    new_order = Order.new(date: DateTime.now, user_id: session[:current_user_id], total: total)
    if new_order.save
      cart = session[:cart]
      cart.each do |item|
        quantity = item["quantity"]
        menu_item_id = item["menu_item_id"]
        menu_item = MenuItem.find(menu_item_id)
        new_order_item = OrderItem.new(order_id: new_order.id,
                                       menu_item_id: menu_item_id, quantity: quantity, menu_item_name: menu_item.name, menu_item_price: menu_item.price)
        new_order_item.save
      end
      session[:cart] = []
      redirect_to order_path(id: new_order.id), notice: "Order was successfully created.Thank you for placing an order with us!"
    else
      flash[:error] = new_order.errors.full_messages.join(", ")
      redirect_to cart_path
    end
  end

  def show
    @order = Order.find(params[:id])
    @order_items = OrderItem.where(order_id: params[:id])
  end

  def update
    order_id = params[:id]
    order = Order.find(order_id)
    order.delivered_at = DateTime.now
    if order.save
      redirect_to owner_path, notice: "Order was successfully updated!"
    else
      flash[:error] = order.errors.full_messages.join(", ")
      redirect_to owner_path
    end
  end
end

app/controllers/owner_controller.rb
class OwnerController < ApplicationController
  def index
    @users = User.all.reject { |user| user.role == "owner" }
    @menus = Menu.all
    @undelivered_orders = Order.where(delivered_at: nil)
    if !Menu.exists?(active: true)
      flash[:error] = "Set a menu to be active!"
    end
    render "index"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in
  skip_before_action :ensure_user_is_owner

  def create
    name = params[:name].capitalize
    email = params[:email]
    password = params[:password]
    user = User.new(name: name, email: email, password: password, role: "customer")
    if user.save
      session[:current_user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = user.errors.full_messages.join(", ")
      redirect_to new_user_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :ensure_user_logged_in
  skip_before_action :ensure_user_is_owner

  def index
    if current_user
      user = current_user
      if user.role == "customer"
        session[:cart] = []
        redirect_to customer_path
      elsif user.role == "owner"
        redirect_to owner_path
      end
    else
      render "index"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/owner_helper.rb
module OwnerHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/owner/_all_users.html.erb
<h2 class=" pb-10  text-4xl">All Users</h2>
<% if users.any? %>
  <table class="table-auto">
    <thead>
      <tr class="text-center underline">
        <th class="p-4 " >ID</th>
        <th class="p-4 ">Created On</th>
        <th class="p-4 " >Name</th>
      </tr>
    </thead>
    <tbody>
      <% users.each do |user| %>
        <tr class="text-center">
          <td class="p-4 " ><%= user.id%></td>
          <td class="p-4 "><%= user.created_at.to_date %></td>
          <td class="p-4 "><%= user.name.capitalize %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class="text-red-600  ">No users!</p>
<% end %>

app/views/owner/_menus.html.erb
<h2 class=" pb-10  text-4xl">All Menus</h2>
<% if menus.any? %>
  <% menus.each do |menu| %>
    <% if menu.active==true %>
      <%= link_to menu.name.capitalize ,menu_path(id: menu.id),class: "btn text-2xl text-center py-4 px-14  my-4 bg-blue-400 border-8 border-green-400" %>
    <% else %>
      <%= link_to menu.name.capitalize ,menu_path(id: menu.id),class: "btn text-2xl text-center py-4 px-14  my-4 bg-blue-400 " %>
    <% end %>
  <% end %>
<% end %>
<%= link_to "Create new menu",new_menu_path,class:  " btn text-2xl text-center py-4 px-10  my-4" %>

app/views/owner/_pending_orders.html.erb
<h2 class=" pb-10  text-4xl mt-10">Orders to be delivered</h2>
<% if undelivered_orders.any? %>
  <table class="table-auto">
    <thead>
      <tr class="text-center underline">
        <th class="p-4 ">ID</th>
        <th class="p-4 ">User ID</th>
        <th class="p-4 ">Date ordered</th>
        <th class="p-4 ">Total</th>
        <th class="p-6 "></th>
      </tr>
    </tr>
  </thead>
  <tbody>
    <% undelivered_orders.each do |order| %>
      <tr class="text-center">
        <td class="p-4 border-4 rounded-xl"><%= link_to order.id,order_path(order.id)%></td>
        <td class="p-4 "><%= order.user_id%></td>
        <td class="p-4 "><%= order.date.to_date%></td>
        <td class="p-4 ">$<%= order.total %></td>
        <td >
          <%= link_to image_tag("https://img.icons8.com/cute-clipart/64/000000/checked.png",alt: "check-mark"),order_path(id:order.id),method: "patch"%></td>
      </tr>
    <% end%>
  </tbody>
</table>
<% else %>
  <p class="text-red-600">No undelivered orders!</p>
<% end%>

app/views/owner/index.html.erb
<div class="flex-row flex">
  <section class="flex flex-col ml-10">
    <%= render partial: "all_users" ,locals:{users:@users}%>
    <%= render partial: "pending_orders" ,locals:{undelivered_orders: @undelivered_orders}%>
  </section>
  <section class="flex flex-col mx-40 ">
    <%= render partial: "menus" ,locals:{menus: @menus}%>
  </section>
</div>

app/views/welcome/index.html.erb
<h1 class="text-center "> Best cafeteria food on the planet!</h1>
<div class=" m-auto my-12 text-center">
  <div class="my-14"><%= link_to "Sign up here!",new_user_path ,class: " btn px-8 py-2 text-3xl" %></div>
  <div class=" "><%= link_to "Login here!",new_sessions_path ,class: "btn  px-8 py-2  text-3xl" %></div>
</div>