config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  resources :orders
  resources :menu_items
  resources :menus
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "welcome#index"

  get "/signin", to: "sessions#new", as: :new_sessions
  post "/signin", to: "sessions#create", as: :sessions
  delete "/signout", to: "sessions#destroy", as: :destroy_sessions

  get "/owner", to: "owner#index", as: :owner
  get "/customer", to: "customer#index", as: :customer
  get "/cart", to: "cart#index", as: :cart
  patch "/cart", to: "cart#update", as: :update_cart
  put "/cart", to: "cart#delete_item", as: :delete_cart_item
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :menu_items
  validates :name, presence: true
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :menu
  has_many :order_items
  validates :name, presence: true
  validates :price, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :menu_item
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :orders
  validates :email, presence: true
  validates :password, presence: true
  validates :password, length: { minimum: 5 }
  validates :name, presence: true
  validates :email, uniqueness: true
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  skip_before_action :ensure_user_is_owner

  def index
    @cart = session[:cart]
    @total = 0
    if @cart
      @cart.each do |cartItem|
        price = MenuItem.find(cartItem["menu_item_id"]).price
        @total += price * cartItem["quantity"]
      end
    end
  end

  def update
    menu_item_id = params[:id]
    quantity = params[:quantity].to_i
    if quantity < 1
      flash[:error] = "Please add atleast one item!"
      redirect_to menu_item_path(menu_item_id) and return
    end
    if session[:cart].any? { |item| item["menu_item_id"] == menu_item_id }
      session[:cart].map { |item| item["quantity"] += quantity if item["menu_item_id"] == menu_item_id }

      redirect_to cart_path, notice: "Added #{quantity} more of #{MenuItem.find(menu_item_id).name} to cart!"
    else
      session[:cart].push({ "menu_item_id" => menu_item_id, "quantity" => quantity.to_i })
      redirect_to cart_path, notice: "Added #{MenuItem.find(menu_item_id).name} to cart!"
    end
  end

  def delete_item
    menu_item_id = params[:id]
    session[:cart].reject! { |item| item["menu_item_id"] == menu_item_id }
    redirect_to cart_path, notice: "Deleted  #{MenuItem.find(menu_item_id).name} from cart!"
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    @menus = Menu.all

    render "index"
  end

  def create
    name = params[:name].capitalize
    menu = Menu.new(name: name)
    if menu.save
      redirect_to owner_path, notice: "#{name} menu was successfully created!"
    else
      flash[:error] = menu.errors.full_messages.join(", ")
      redirect_to new_menu_path
    end
  end

  def show
    @is_owner = ensure_user_is_owner
    @current_menu_id = params[:id]
    @menu_items = MenuItem.where(menu_id: @current_menu_id, deletable: nil)
    @menu = Menu.find(@current_menu_id)
    if MenuItem.where(menu_id: @current_menu_id, deletable: nil).empty?
      @menu.active = nil
      @menu.save
      flash[:error] = "#{@menu.name} menu is empty! Setting it to inactive!"
    end
    render "show"
  end

  def update
    active_status = params[:active]
    menu = Menu.find(params[:id])
    if active_status
      if Menu.where(active: true).any?
        flash[:error] = "#{Menu.find_by(active: true).name} menu is already active!"
        redirect_to menu_path(params[:id]) and return
      elsif MenuItem.where(menu_id: menu.id, deletable: nil).empty?
        flash[:error] = "#{menu.name} menu is empty! Cannot set it active!"
        redirect_to menu_path(params[:id]) and return
      end
    end
    menu.active = active_status
    menu.save
    redirect_to menu_path(:id => menu.id), notice: "#{menu.name.capitalize} menu was successfully set #{active_status ? true : false}!"
  end
end

app/controllers/owner_controller.rb
class OwnerController < ApplicationController
  def index
    @users = User.all.reject { |user| user.role == "owner" }
    @menus = Menu.all
    @undelivered_orders = Order.where(delivered_at: nil)
    if !Menu.exists?(active: true)
      flash[:error] = "Set a menu to be active!"
    end
    render "index"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in
  skip_before_action :ensure_user_is_owner

  def create
    name = params[:name].capitalize
    email = params[:email]
    password = params[:password]
    user = User.new(name: name, email: email, password: password, role: "customer")
    if user.save
      session[:current_user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = user.errors.full_messages.join(", ")
      redirect_to new_user_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/owner_helper.rb
module OwnerHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCMS</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class=" fixed flex flex-col bg-black min-h-full text-white text-center ">
      <% if @current_user %>
        <%if @current_user.role=="owner" %>
          <%= link_to "myCMS" ,owner_path ,class:"m-5 text-5xl font-black" %>
        <% else %>
          <%= link_to "myCMS" ,customer_path ,class:"m-5 text-5xl font-black" %>
        <% end %>
        <p class=" text-base py-8 ">Logged in as:
          <br>
          <%= @current_user.name.capitalize %></br>
        (<%= @current_user.role%>)</p>
      <%if @current_user.role=="customer" %>
        <%= link_to "Your orders",orders_path, class: "py-4 px-8 text-base mx-4 underline mt-auto" %>
        <%= link_to image_tag("https://img.icons8.com/cute-clipart/64/000000/shopping-cart-loaded.png", alt: 'Cart-icon'),cart_path,class:"mx-auto mt-auto "%>
      <%else %>
        <%= link_to "All orders",orders_path ,class: "py-4 px-8 text-base mx-4 underline mt-auto" %>
      <% end %>
      <%= link_to "Signout",destroy_sessions_path ,method: "delete",class: "btn py-4 px-8 text-base mx-4 mt-auto mb-4" %>
    <%else %>
      <%= link_to "myCMS" ,root_path ,class:"m-5 text-5xl font-black" %>
    <%end%>
  </div>
  <div class="max-w-5xl flex  ml-60 flex-col align-items-center justify-center ">
    <section class="m-10  text-center">
      <% if flash[:error] %>
        <p class="text-red-600"><%= flash[:error] %></p>
      <% end %>
      <% if flash[:notice] %>
        <p class="text-green-600"><%= flash[:notice] %></p>
      <% end %>
    </section>
    <%= yield %>
  </div>
</body>
</html>